num_vec <- c(10, 20, 30, 40)
print(num_vec)
print(typeof(num_vec))
char_vec <- c("Apple", "Banana", "Cherry")
print(char_vec)
print(typeof(char_vec))
log_vec <- c(TRUE, FALSE, TRUE, FALSE)
print(log_vec)
print(typeof(log_vec))
